const test = require('node:test');
const assert = require('node:assert/strict');
const { app } = require('../backend/server');
const logger = require('../backend/utils/logger');
const { downloadProgress, DownloadProgress } = require('../backend/services/progressTracker');

let server;
let baseUrl;

test.before(async () => {
  await new Promise((resolve) => {
    server = app.listen(0, '127.0.0.1', () => {
      baseUrl = `http://127.0.0.1:${server.address().port}`;
      resolve();
    });
  });
});

test.after(async () => {
  await new Promise((resolve) => server.close(resolve));
  logger.close();
});

test('serves the existing frontend and security headers', async () => {
  const response = await fetch(baseUrl);
  assert.equal(response.status, 200);
  assert.equal(response.headers.get('x-content-type-options'), 'nosniff');
  const html = await response.text();
  assert.match(html, /YT-DL Studio/);
  assert.match(html, /speed-history-canvas/);
  assert.match(html, /video-stream-row/);
  assert.match(html, /audio-stream-row/);

  const chartModule = await fetch(`${baseUrl}/js/speed-chart.js`);
  assert.equal(chartModule.status, 200);
  assert.match(await chartModule.text(), /export function updateSpeedChart/);
});

test('download status exposes independent video and audio stream state', async () => {
  const id = 'stream-contract-test';
  const progress = new DownloadProgress(id, { expectedVideo: true, expectedAudio: false });
  progress.videoProgress.status = 'downloading';
  progress.videoProgress.progress = 42;
  downloadProgress.set(id, progress);

  try {
    const response = await fetch(`${baseUrl}/api/download/${id}/status`);
    assert.equal(response.status, 200);
    const payload = await response.json();
    assert.equal(payload.video_progress.progress, 42);
    assert.equal(payload.video_progress.expected, true);
    assert.equal(payload.audio_progress.status, 'not_requested');
    assert.equal(payload.audio_progress.expected, false);
  } finally {
    downloadProgress.delete(id);
  }
});

test('command preview is generated by the backend command builder', async () => {
  const response = await fetch(`${baseUrl}/api/command-preview`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ url: 'https://example.com/video', filename: '%(title)s', outputFormat: 'mp4' }),
  });
  assert.equal(response.status, 200);
  const payload = await response.json();
  assert.match(payload.command, /--progress-template/);
  assert.match(payload.command, /--merge-output-format mp4/);
});

test('dangerous command options are rejected', async () => {
  const response = await fetch(`${baseUrl}/api/command-preview`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ url: 'https://example.com/video', advancedSettings: { exec: 'whoami' } }),
  });
  assert.equal(response.status, 400);
  assert.equal((await response.json()).code, 'DANGEROUS_OPTION_DISABLED');
});

test('custom output paths and untrusted browser origins are rejected', async () => {
  const pathResponse = await fetch(`${baseUrl}/api/command-preview`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ url: 'https://example.com/video', downloadPath: 'C:/Windows/Temp' }),
  });
  assert.equal(pathResponse.status, 400);
  assert.equal((await pathResponse.json()).code, 'CUSTOM_PATH_DISABLED');

  const originResponse = await fetch(`${baseUrl}/api/downloads`, {
    headers: { Origin: 'https://evil.example' },
  });
  assert.equal(originResponse.status, 403);
  assert.equal((await originResponse.json()).code, 'ORIGIN_NOT_ALLOWED');
});

test('private-network metadata URLs are blocked before yt-dlp is started', async () => {
  const response = await fetch(`${baseUrl}/api/info?url=${encodeURIComponent('http://127.0.0.1/private')}`);
  assert.equal(response.status, 400);
  assert.equal((await response.json()).error_code, 'PRIVATE_URL_NOT_ALLOWED');
});

test('unknown API endpoints return structured 404 responses', async () => {
  const response = await fetch(`${baseUrl}/api/missing`);
  assert.equal(response.status, 404);
  assert.equal((await response.json()).code, 'NOT_FOUND');
});
